# Generated by Django 3.2.3 on 2021-06-01 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_photos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6db32376-f07e-4ed4-980d-6b53f2be33cc'), primary_key=True, serialize=False),
        ),
    ]
