# Generated by Django 3.2.3 on 2021-06-01 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_photos_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('56659fef-d333-497a-a834-69fc0294be37'), primary_key=True, serialize=False),
        ),
    ]
