# Generated by Django 3.2.3 on 2021-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_photos_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
