# Generated by Django 3.2.3 on 2021-06-01 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_photos_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2452219f-78d8-4ec0-8cc6-e9d7baaee96d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
