# Generated by Django 3.2.3 on 2021-06-01 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210601_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb4337f9-54e3-4dcf-87b1-785139b5d807'), editable=False, primary_key=True, serialize=False),
        ),
    ]
