# Generated by Django 3.2.3 on 2021-06-01 02:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210601_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c256cec-1bbb-4703-9184-2f05e69dc36c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
