# Generated by Django 3.2.3 on 2021-06-01 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_photos_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
