# Generated by Django 3.2.3 on 2021-06-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_photos_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='description',
            new_name='name',
        ),
    ]
