# Generated by Django 3.2.3 on 2021-06-01 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_description_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='core.album'),
        ),
    ]
